### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ilyar** [bem-incubator/bem-tools-create#2]
После исправления https://github.com/bem-incubator/bem-tools-create/pull/1 получил ошибку:
```log
[SyntaxError: /home/ilyar/.nvm/versions/node/v0.12.9/lib/node_modules/bem-tools-create/lib/create.js:17
    entities.forEach(entity => {
                            ^^
Unexpected token =>]
```
Воспроизведение:
```bash
$ node -v && npm -v
v0.12.9
2.14.9
$ npm i -g bem/bem-tools#WIP
$ npm i -g ilyar/bem-tools-create#08d09de
$ bem
```

**Comment by tadatuta** [comment]
Есть такое, перепишу на ES5 в ближайшее время.
Пока могу рекомендовать использовать `nvm` и `node 5`.

**Comment by ilyar** [comment]
> Пока могу рекомендовать использовать nvm и node 5.

ок, понятно.

Еще хочется понять, какая стратегия по поддержке версий node?

**Comment by tadatuta** [comment]
> Еще хочется понять, какая стратегия по поддержке версий node?

`0.12` пока будем поддерживать

**Comment by tadatuta** [comment]
Исправлено в https://github.com/bem-incubator/bem-tools-create/commit/717180fc5c061c6d73f987ddc3b1baff49095d40, спасибо за репорт!
