### ISSUE TITLE
Support one extention in curly braces

### ISSUE THREAD

**Issue by tadatuta** [bem-incubator/bem-tools-create#3]
` bem create b1.{ext}` results with `b1.{ext}` file created but `b1.ext` expected

**Comment by vithar** [comment]
b1.ext is not expected here. Module brace-expansion mimics bash behavior:

> touch b.{css,js} b.{ext} && ls -la b*
-rw-r--r--  1 vitaly  admin  0  3 янв 10:24 b.css
-rw-r--r--  1 vitaly  admin  0  3 янв 10:24 b.js
-rw-r--r--  1 vitaly  admin  0  3 янв 10:24 b.{ext}

I think we should do the same.

**Comment by tadatuta** [comment]
sounds reasonable
